// Contract addresses - will be auto-generated by genabi script
export const CONTRACT_ADDRESSES = {
  localhost: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512", // Hardhat localhost deployment (2025-11-10)
  sepolia: "0xf5c1F62b602cCf3545ff5ed90e7eC7032915fE8D", // Deployed on 2025-11-10
} as const;

export function getContractAddress(chainId: number): string {
  switch (chainId) {
    case 31337: // Localhost
      return CONTRACT_ADDRESSES.localhost;
    case 11155111: // Sepolia
      return CONTRACT_ADDRESSES.sepolia;
    default:
      throw new Error(`Unsupported chain ID: ${chainId}`);
  }
}

